version: "3"

services:
  db:
    image: postgres:11.0-alpine
    volumes:
      - ./stocks_products/data:/stocks_products/data
    ports:
      - "5432:5432"
    environment:
#      - POSTGRES_DB=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=my-db-stocks
      - POSTGRES_USER=admin_stocks
      - POSTGRES_PASSWORD=stocks
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./stocks_products:/stocks_products
    ports:
      - "8000:8000"
    depends_on:
      - db
